# Generated by Django 3.1.4 on 2020-12-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photonyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
