# Generated by Django 3.1.4 on 2020-12-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photonyc', '0003_auto_20201207_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='loaction',
            new_name='location',
        ),
    ]
